name: CI
on:
  pull_request:
    branches: [master]

jobs:
  Unit:
    runs-on: ubuntu-latest
    - uses: actions/checkout@v2
    - name: Installing dependencies
      run: npm i
    - name: Running unit tests
      run: npm run unit-tests