name: Deployment BOT
on:
  push: 
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Installing dependencies
      run: npm install
    - name: Build
      run: npm run build
    - name: Deploying version
      uses: danitseitlin/package-deployer@master
      with:
        pkg_name: html-scrapper-ts
        pkg_managers: '[github, npm]'
        npm_access_token: ${{secrets.NPM_AUTH_TOKEN}}
        github_access_token: ${{secrets.G_AUTH_TOKEN}}